name: null
favicon: null
layout_spectrum: 0.02080719033256173
typography_spectrum: 0.008955810684710741
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6057137562893331
  lightness: 0.3456715743523091
  saturation: 0.20943453488871455
  rhythmicContrast: 0.023482301738113165
purpose: []
